name: .NET Core

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      hub:
        image: selenium/hub:3.141.59-20200409
        ports:
          - "4444:4444"
      chrome:
        image: selenium/node-chrome:3.141.59-20200409
        volumes:
          - /dev/shm:/dev/shm
        env:
          HUB_HOST: hub
          HUB_PORT: 4444

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore ./src/Hippopotamus.sln
    - name: Build
      run: dotnet build ./src/Hippopotamus.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ./src/Hippopotamus.sln --no-build --configuration Release --verbosity normal
